-- MySQL Script generated by MySQL Workbench
-- Thu Mar 19 06:31:34 2020
-- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema newji_development
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `newji_development`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ユーザId',
  `email` VARCHAR(100) NOT NULL DEFAULT "" COMMENT 'ログインメールアドレス',
  `encrypted_password` VARCHAR(255) NOT NULL DEFAULT "" COMMENT 'ログインパスワード',
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `accept_flg` INT(1) NULL DEFAULT NULL COMMENT '利用規約',
  `antiforce_flg` INT(1) NULL DEFAULT NULL COMMENT '反社会勢力',
  `access_IP` VARCHAR(45) NULL,
  `reset_password_token` VARCHAR(255) NULL,
  `reset_password_sent_at` TIMESTAMP NULL,
  `remember_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `creator` BIGINT(20) NULL DEFAULT NULL COMMENT '登録者Id',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日',
  `updater` BIGINT(20) NULL DEFAULT NULL COMMENT '最終更新者Id',
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最終更新日',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '削除時点 Deleted time',
  PRIMARY KEY (`id`),
  INDEX `mail_idx` (`email` ASC),
  UNIQUE `mail_password_reset_token_UNIQUE` (`email`, `reset_password_token` ASC)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'ユーザテーブル';

-- -----------------------------------------------------
-- Table `profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `profiles` ;

CREATE TABLE IF NOT EXISTS `profiles` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'プロバイダーId',
  `buyer_id` BIGINT(20),
  `supplier_id` BIGINT(20),
  `buyer_supplier_id` BIGINT(20),
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `first_name` VARCHAR(40) NULL DEFAULT NULL COMMENT 'プロバイダー名',
  `last_name` VARCHAR(40) NULL DEFAULT NULL COMMENT 'プロバイダー別姓',
  `tel` VARCHAR(15) NULL DEFAULT NULL COMMENT 'プロバイダーTEL',
  `company_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '会社名',
  `code` VARCHAR(45) NULL DEFAULT NULL COMMENT '会社番号',
  `logo` VARCHAR(45) NULL,
  `department` VARCHAR(50) NULL DEFAULT NULL COMMENT '部署名',
  `position` VARCHAR(30) NULL DEFAULT NULL COMMENT '役職',
  `creator` BIGINT(20) NULL DEFAULT NULL COMMENT '登録者Id',
  `contract_status` VARCHAR(45) NULL DEFAULT '' COMMENT 'NDA契約済み', -- nda_signed default 0: not sign ( or 1: signed )
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日',
  `updater` BIGINT(20) NULL DEFAULT NULL COMMENT '最終更新者Id',
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最終更新日',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '削除時点 Deleted time',
  PRIMARY KEY (`id`)
  -- ,
  -- UNIQUE INDEX `user_type_UNIQUE` (`type` ASC)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'プロバイダー詳細テーブル';

-- -----------------------------------------------------
-- Table `inspection_requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inspection_requests` ;

CREATE TABLE IF NOT EXISTS `inspection_requests` (
  `id` BIGINT(20) NOT NULL,
  `buyer_id` BIGINT(20) NULL,
  `request_date` DATE NULL,
  `request_type` TINYINT(3) NULL,
  `inspect_company_name` VARCHAR(45) NULL,
  `inspect_pic_name` VARCHAR(45) NULL,
  `inspect_address` VARCHAR(45) NULL,
  `inspect_tel` VARCHAR(11) NULL,
  `inspection_result` TINYINT(3) NULL,
  `inspection_result_detail` VARCHAR(45) NULL,
  `result_issued_date` DATE NULL,
  `users_id` BIGINT(20) NOT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '削除時点 Deleted time',
  PRIMARY KEY (`id`),
  INDEX `fk_inspection_requests_users1_idx` (`users_id` ASC)
  )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `item_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_info` ;

CREATE TABLE IF NOT EXISTS `item_info` (
  `id` BIGINT(20) NOT NULL COMMENT '項目情報Id',
  `SKU` VARCHAR(45) NULL,
  `info_sku` VARCHAR(2000) NULL DEFAULT NULL COMMENT '項目説明情報',
  `name` VARCHAR(100) NULL,
  `info_name` VARCHAR(2000) NULL,
  `category1` VARCHAR(1000) NULL DEFAULT NULL,
  `category2` VARCHAR(1000) NULL DEFAULT NULL,
  `category3` VARCHAR(1000) NULL DEFAULT NULL,
  `info_category` VARCHAR(2000) NULL DEFAULT NULL COMMENT '項目説明情報',
  `expected_sales_volume` INT(11) NULL DEFAULT NULL,
  `info_expected_sales_volume` VARCHAR(2000) NULL DEFAULT NULL COMMENT '項目説明情報',
  `lead_time` VARCHAR(45) NULL DEFAULT NULL,
  `info_lead_time` VARCHAR(2000) NULL,
  `creator` BIGINT(20) NULL DEFAULT NULL COMMENT '登録者Id',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日',
  `updater` BIGINT(20) NULL DEFAULT NULL COMMENT '最終更新者Id',
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最終更新日',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '削除時点 Deleted time',
  PRIMARY KEY (`id`)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '項目情報テーブル';

-- -----------------------------------------------------
-- Table `requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `requests` ;

CREATE TABLE IF NOT EXISTS `requests` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '依頼Id',
  `buyer_id` BIGINT(20) NOT NULL COMMENT '購入者Id',
  `supplier_id` BIGINT(20) NOT NULL COMMENT '供給者Id',
  `request_status` INT(6) NOT NULL COMMENT '登録進捗Id',
  `submitted_date` DATE NULL,
  `request_by` DATE NULL,
  `creator` BIGINT(20) NULL DEFAULT NULL COMMENT '登録者Id',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日',
  `updater` BIGINT(20) NULL DEFAULT NULL COMMENT '最終更新者Id',
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最終更新日',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '削除時点 Deleted time',
  PRIMARY KEY (`id`),
  INDEX `fk_request_users1_idx` (`buyer_id` ASC)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '依頼テーブル';

-- -----------------------------------------------------
-- Table `item_drawings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_drawings` ;

CREATE TABLE IF NOT EXISTS `item_drawings` (
  `id` BIGINT(20) NOT NULL COMMENT '項目図面Id',
  `category_id` BIGINT(20) NULL COMMENT '項目図面ファイルId',
  `info` VARCHAR(2000) NULL DEFAULT NULL COMMENT '項目図面説明情報',
  `creator` BIGINT(20) NULL DEFAULT NULL COMMENT '登録者Id',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日',
  `updater` BIGINT(20) NULL DEFAULT NULL COMMENT '最終更新者Id',
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最終更新日',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '削除時点 Deleted time',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '項目図面テーブル';

-- -----------------------------------------------------
-- Table `item_qualities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_qualities` ;

CREATE TABLE IF NOT EXISTS `item_qualities` (
  `id` BIGINT(20) NOT NULL COMMENT '項目品質Id',
  `quality1` INT(1) NULL DEFAULT '0' COMMENT '項目品質1',
  `info1` VARCHAR(500) NULL DEFAULT NULL COMMENT '品質情報1',
  `quality2` INT(1) NULL DEFAULT '0' COMMENT '項目品質2',
  `info2` VARCHAR(500) NULL DEFAULT NULL COMMENT '品質情報2',
  `quality3` INT(1) NULL DEFAULT '0' COMMENT '項目品質3',
  `info3` VARCHAR(500) NULL DEFAULT NULL COMMENT '品質情報3',
  `quality4` INT(1) NULL DEFAULT '0' COMMENT '項目品質4',
  `info4` VARCHAR(500) NULL DEFAULT NULL COMMENT '品質情報4',
  `quality5` INT(1) NULL DEFAULT '0' COMMENT '項目品質5',
  `info5` VARCHAR(500) NULL DEFAULT NULL COMMENT '品質情報5',
  `quality6` INT(1) NULL DEFAULT '0' COMMENT '項目品質6',
  `info6` VARCHAR(500) NULL DEFAULT NULL COMMENT '品質情報6',
  `quality7` INT(1) NULL DEFAULT '0' COMMENT '項目品質7',
  `info7` VARCHAR(500) NULL DEFAULT NULL COMMENT '品質情報7',
  `quality8` INT(1) NULL DEFAULT '0' COMMENT '項目品質8',
  `info8` VARCHAR(500) NULL DEFAULT NULL COMMENT '品質情報8',
  `quality9` INT(1) NULL DEFAULT '0' COMMENT '項目品質9',
  `info9` VARCHAR(500) NULL DEFAULT NULL COMMENT '品質情報9',
  `quality10` INT(1) NULL DEFAULT '0' COMMENT '項目品質10',
  `info10` VARCHAR(500) NULL DEFAULT NULL COMMENT '品質情報10',
  `quality11` INT(1) NULL DEFAULT '0' COMMENT '項目品質11',
  `info11` VARCHAR(500) NULL DEFAULT NULL COMMENT '品質情報11',
  `quality12` INT(1) NULL DEFAULT '0' COMMENT '項目品質12',
  `info12` VARCHAR(500) NULL DEFAULT NULL COMMENT '品質情報12',
  `quality13` INT(1) NULL DEFAULT '0' COMMENT '項目品質13',
  `info13` VARCHAR(500) NULL DEFAULT NULL COMMENT '品質情報13',
  `quality14` INT(1) NULL DEFAULT '0' COMMENT '項目品質14',
  `info14` VARCHAR(500) NULL DEFAULT NULL COMMENT '品質情報14',
  `quality15` INT(1) NULL DEFAULT '0' COMMENT '項目品質15',
  `info15` VARCHAR(500) NULL DEFAULT NULL COMMENT '品質情報15',
  `quality16` INT(1) NULL DEFAULT '0' COMMENT '項目品質16',
  `info16` VARCHAR(500) NULL DEFAULT NULL COMMENT '品質情報16',
  `creator` BIGINT(20) NULL DEFAULT NULL COMMENT '登録者Id',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日',
  `updater` BIGINT(20) NULL DEFAULT NULL COMMENT '最終更新者Id',
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最終更新日',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '削除時点 Deleted time',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '項目品質テーブル';

-- -----------------------------------------------------
-- Table `item_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_images` ;

CREATE TABLE IF NOT EXISTS `item_images` (
  `id` BIGINT(20) NOT NULL COMMENT '項目画面Id',
  `category_id` BIGINT(20) NULL COMMENT '項目画面ファイルId',
  `info` VARCHAR(2000) NULL DEFAULT NULL COMMENT '項目画面説明情報',
  `creator` BIGINT(20) NULL DEFAULT NULL COMMENT '登録者Id',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日',
  `updater` BIGINT(20) NULL DEFAULT NULL COMMENT '最終更新者Id',
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最終更新日',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '削除時点 Deleted time',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '項目画面テーブル';

-- -----------------------------------------------------
-- Table `item_samples`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_samples` ;

CREATE TABLE IF NOT EXISTS `item_samples` (
  `id` BIGINT(20) NOT NULL COMMENT '項目サンプルId',
  `category_id` BIGINT(20) NULL COMMENT '項目サンプルファイルId',
  `info` VARCHAR(2000) NULL DEFAULT NULL COMMENT '項目サンプル説明情報',
  `creator` BIGINT(20) NULL DEFAULT NULL COMMENT '登録者Id',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日',
  `updater` BIGINT(20) NULL DEFAULT NULL COMMENT '最終更新者Id',
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最終更新日',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '削除時点 Deleted time',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '項目サンプルテーブル';

-- -----------------------------------------------------
-- Table `item_requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_requests` ;

CREATE TABLE IF NOT EXISTS `item_requests` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '依頼Id',
  `request_id` BIGINT(20) NOT NULL COMMENT '項目Id',
  `item_info_id` BIGINT(20) NULL COMMENT '項目情報Id',
  `item_draw_id` BIGINT(20) NULL,
  `item_image_id` BIGINT(20) NULL,
  `quality_id` BIGINT(20) NULL COMMENT '項目品質Id',
  `quality_info` VARCHAR(2000) NULL DEFAULT NULL COMMENT '項目品質説明情報',
  `standard_id` BIGINT(20) NULL DEFAULT NULL COMMENT '項目基準Id',
  `standard_info` VARCHAR(2000) NULL DEFAULT NULL COMMENT '項目基準説明情報',
  `condition_id` BIGINT(20) NULL DEFAULT NULL COMMENT '項目条件Id',
  `item_sample_id` BIGINT(20) NULL COMMENT '項目金型Id',
  `quotation_id` BIGINT(20) NULL DEFAULT NULL COMMENT '項目見積Id',
  `creator` BIGINT(20) NULL DEFAULT NULL COMMENT '登録者Id',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日',
  `updater` BIGINT(20) NULL DEFAULT NULL COMMENT '最終更新者Id',
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最終更新日',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '削除時点 Deleted time',
  PRIMARY KEY (`id`),
  INDEX `fk_request_item_info_idx` (`item_info_id` ASC) ,
  INDEX `fk_item_request_request1_idx` (`request_id` ASC) ,
  INDEX `fk_item_drawing_item_request1_idx` (`item_draw_id` ASC) ,
  INDEX `fk_item_quality_item_request1_idx` (`quality_id` ASC) ,
  INDEX `fk_item_request_item_image1_idx` (`item_image_id` ASC) ,
  INDEX `fk_item_request_item_sample1_idx` (`item_sample_id` ASC)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '依頼テーブル';

-- -----------------------------------------------------
-- Table `item_conditions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_conditions` ;

CREATE TABLE IF NOT EXISTS `item_conditions` (
  `id` BIGINT(20) NOT NULL,
  `item_id` BIGINT(20) NOT NULL,
  `condition` VARCHAR(2000) NULL DEFAULT NULL COMMENT '項目条件情報',
  `position` TINYINT(3) NULL,
  `type` TINYINT(3) NULL,
  `creator` BIGINT(20) NULL DEFAULT NULL COMMENT '登録者Id',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日',
  `updater` BIGINT(20) NULL DEFAULT NULL COMMENT '最終更新者Id',
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最終更新日',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '削除時点 Deleted time',
  PRIMARY KEY (`id`),
  INDEX `fk_item_conditions_item_request1_idx` (`item_id` ASC)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '項目条件情報';

-- -----------------------------------------------------
-- Table `contracts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contracts` ;

CREATE TABLE IF NOT EXISTS `contracts` (
  `id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `contract_type` TINYINT(3) NULL,
  `contract_status` VARCHAR(45) NULL,
  `contract_file` VARCHAR(45) NULL,
  `contract_date` DATE NULL,
  `profile_id` BIGINT(20) NOT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '削除時点 Deleted time',
  PRIMARY KEY (`id`),
  INDEX `fk_buyer_contracts_profile1_idx` (`profile_id` ASC, `user_id` ASC)
  )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `user_calendars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_calendars` ;

CREATE TABLE IF NOT EXISTS `user_calendars` (
  `id` BIGINT(20) NOT NULL COMMENT '項目カレンダーId',
  `user_id` BIGINT(20) NOT NULL COMMENT 'ユーザId',
  `type` INT(11) NULL,
  `title` VARCHAR(45) NULL,
  `occur_date` DATETIME NULL DEFAULT NULL COMMENT 'イベント日',
  `content` VARCHAR(2000) NULL DEFAULT NULL COMMENT 'イベント内容',
  `occur_time_from` INT NULL,
  `occur_time_to` VARCHAR(45) NULL,
  `creator` BIGINT(20) NULL DEFAULT NULL COMMENT '登録者Id',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日',
  `updater` BIGINT(20) NULL DEFAULT NULL COMMENT '最終更新者Id',
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最終更新日',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '削除時点 Deleted time',
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_user_calendar_users1_idx` (`user_id` ASC)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '項目カレンダーテーブル';

-- -----------------------------------------------------
-- Table `image_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `image_categories` ;

CREATE TABLE IF NOT EXISTS `image_categories` (
  `id` BIGINT(20) NOT NULL COMMENT '項目画面Id',
   `item_image_id` BIGINT(20) NOT NULL,
  `image_info` VARCHAR(2000) NULL DEFAULT NULL COMMENT '項目画面説明情報',
  `creator` BIGINT(20) NULL DEFAULT NULL COMMENT '登録者Id',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日',
  `updater` BIGINT(20) NULL DEFAULT NULL COMMENT '最終更新者Id',
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最終更新日',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '削除時点 Deleted time',
  PRIMARY KEY (`id`),
  INDEX `fk_image_category_item_image1_idx` (`item_image_id` ASC)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '項目画面テーブル';

-- -----------------------------------------------------
-- Table `file_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `file_images` ;

CREATE TABLE IF NOT EXISTS `file_images` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ファイルId',
  `item_category` BIGINT(8) NOT NULL,
  `item_image_id` BIGINT(20) NOT NULL COMMENT 'Item Draw/Image/Sample Id\n',
  `file_link` VARCHAR(255) NOT NULL COMMENT 'ファイルリンク',
  `file_name` VARCHAR(255) NULL COMMENT 'ファイルタイプ',
  `creator` BIGINT(20) NULL DEFAULT NULL COMMENT '登録者Id',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日',
  `updater` BIGINT(20) NULL DEFAULT NULL COMMENT '最終更新者Id',
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最終更新日',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '削除時点 Deleted time',
  PRIMARY KEY (`id`),
  INDEX `fk_file_item_image1_idx` (`item_image_id` ASC, `item_category` ASC)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'ファイルテーブル';

-- -----------------------------------------------------
-- Table `draw_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `draw_categories` ;

CREATE TABLE IF NOT EXISTS `draw_categories` (
  `id` BIGINT(20) NOT NULL COMMENT '項目画面Id',
  `item_draw_id` BIGINT(20) NOT NULL,
  `draw_info` VARCHAR(2000) NULL DEFAULT NULL COMMENT '項目画面説明情報',
  `creator` BIGINT(20) NULL DEFAULT NULL COMMENT '登録者Id',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日',
  `updater` BIGINT(20) NULL DEFAULT NULL COMMENT '最終更新者Id',
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最終更新日',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '削除時点 Deleted time',
  PRIMARY KEY (`id`),
  INDEX `fk_draw_category_item_draw_idx` (`item_draw_id` ASC)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '項目画面テーブル';


-- -----------------------------------------------------
-- Table `file_draws`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `file_draws` ;

CREATE TABLE IF NOT EXISTS `file_draws` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ファイルId',
  `item_category` BIGINT(8) NOT NULL,
  `item_draw_id` BIGINT(20) NOT NULL COMMENT 'Item Draw/Image/Sample Id\n',
  `file_link` VARCHAR(255) NOT NULL COMMENT 'ファイルリンク',
  `file_name` VARCHAR(255) NULL COMMENT 'ファイルタイプ',
  `creator` BIGINT(20) NULL DEFAULT NULL COMMENT '登録者Id',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日',
  `updater` BIGINT(20) NULL DEFAULT NULL COMMENT '最終更新者Id',
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最終更新日',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '削除時点 Deleted time',
  PRIMARY KEY (`id`),
  INDEX `fk_file_item_draw1_idx` (`item_draw_id` ASC, `item_category` ASC)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'ファイルテーブル';


-- -----------------------------------------------------
-- Table `sample_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sample_categories` ;

CREATE TABLE IF NOT EXISTS `sample_categories` (
  `id` BIGINT(20) NOT NULL COMMENT '項目画面Id',
  `item_sample_id` BIGINT(20) NOT NULL,
  `sample_info` VARCHAR(2000) NULL DEFAULT NULL COMMENT '項目画面説明情報',
  `creator` BIGINT(20) NULL DEFAULT NULL COMMENT '登録者Id',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日',
  `updater` BIGINT(20) NULL DEFAULT NULL COMMENT '最終更新者Id',
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最終更新日',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '削除時点 Deleted time',
  PRIMARY KEY (`id`),
  INDEX `fk_sample_category_item_sample_idx` (`item_sample_id` ASC)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '項目画面テーブル';


-- -----------------------------------------------------
-- Table `file_samples`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `file_samples` ;

CREATE TABLE IF NOT EXISTS `file_samples` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ファイルId',
  `item_category` BIGINT(8) NOT NULL,
  `item_sample_id` BIGINT(20) NOT NULL COMMENT 'Item Draw/Image/Sample Id\n',
  `file_link` VARCHAR(255) NOT NULL COMMENT 'ファイルリンク',
  `file_name` VARCHAR(255) NULL COMMENT 'ファイルタイプ',
  `creator` BIGINT(20) NULL DEFAULT NULL COMMENT '登録者Id',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日',
  `updater` BIGINT(20) NULL DEFAULT NULL COMMENT '最終更新者Id',
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最終更新日',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '削除時点 Deleted time',
  PRIMARY KEY (`id`),
  INDEX `fk_file_item_sample_idx` (`item_category` ASC, `item_sample_id` ASC)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'ファイルテーブル';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
